name: Deploy member email forwards

on:
  schedule:
    - cron: '14 30 * * *'
  push:
    branches:
      - master
    paths:
      - 'member-emails/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm
      working-directory: member-emails

    - name: Set Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Install dependencies
      run: npm i
      working-directory: member-emails

    - name: Create environment files
      working-directory: member-emails
      run: |
        echo -e "${{ secrets.UNATY_MEMBER_EXPORT_ENV }}" > .env

    - name: Run member email forward creation
      run: npm run deploy
      working-directory: member-emails